/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ltm.admin;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author TUF
 */
public class ManHinhXacNhanXoaCauHoiIQ extends javax.swing.JFrame {

    /**
     * Creates new form ManHinhChoGhepTran
     */
    public ManHinhXacNhanXoaCauHoiIQ() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelXacNhanXoaCauHoi = new javax.swing.JPanel();
        labelXacNhanXoa = new javax.swing.JLabel();
        buttonHuyXoa = new javax.swing.JButton();
        buttonXacNhanXoa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelXacNhanXoaCauHoi.setBackground(new java.awt.Color(255, 255, 255));

        labelXacNhanXoa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelXacNhanXoa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelXacNhanXoa.setText("Xác nhận chắc chắn xoá câu hỏi IQ này?");

        buttonHuyXoa.setBackground(new java.awt.Color(220, 20, 60));
        buttonHuyXoa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonHuyXoa.setForeground(new java.awt.Color(255, 255, 255));
        buttonHuyXoa.setText("Huỷ");
        buttonHuyXoa.setToolTipText("Huỷ");
        buttonHuyXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonHuyXoaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonHuyXoaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonHuyXoaMouseExited(evt);
            }
        });

        buttonXacNhanXoa.setBackground(new java.awt.Color(34, 139, 34));
        buttonXacNhanXoa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonXacNhanXoa.setForeground(new java.awt.Color(255, 255, 255));
        buttonXacNhanXoa.setText("Xác nhận");
        buttonXacNhanXoa.setToolTipText("Xác nhận");
        buttonXacNhanXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonXacNhanXoaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonXacNhanXoaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonXacNhanXoaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelXacNhanXoaCauHoiLayout = new javax.swing.GroupLayout(panelXacNhanXoaCauHoi);
        panelXacNhanXoaCauHoi.setLayout(panelXacNhanXoaCauHoiLayout);
        panelXacNhanXoaCauHoiLayout.setHorizontalGroup(
            panelXacNhanXoaCauHoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelXacNhanXoaCauHoiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelXacNhanXoaCauHoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelXacNhanXoa, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(panelXacNhanXoaCauHoiLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(buttonXacNhanXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(buttonHuyXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelXacNhanXoaCauHoiLayout.setVerticalGroup(
            panelXacNhanXoaCauHoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelXacNhanXoaCauHoiLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(labelXacNhanXoa)
                .addGap(18, 18, 18)
                .addGroup(panelXacNhanXoaCauHoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonHuyXoa)
                    .addComponent(buttonXacNhanXoa))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelXacNhanXoaCauHoi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelXacNhanXoaCauHoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonHuyXoaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHuyXoaMouseEntered
        buttonHuyXoa.setBackground(new Color(178, 34, 34));
    }//GEN-LAST:event_buttonHuyXoaMouseEntered

    private void buttonHuyXoaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHuyXoaMouseExited
        buttonHuyXoa.setBackground(new Color(220, 20, 60));
    }//GEN-LAST:event_buttonHuyXoaMouseExited

    private void buttonHuyXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHuyXoaMouseClicked
        System.exit(0);
    }//GEN-LAST:event_buttonHuyXoaMouseClicked

    private void buttonXacNhanXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonXacNhanXoaMouseClicked
        String noiDungThongBao = "Xoá thành công";
        JOptionPane.showMessageDialog(null, noiDungThongBao, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_buttonXacNhanXoaMouseClicked

    private void buttonXacNhanXoaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonXacNhanXoaMouseEntered
        buttonXacNhanXoa.setBackground(new Color(0, 128, 0));
    }//GEN-LAST:event_buttonXacNhanXoaMouseEntered

    private void buttonXacNhanXoaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonXacNhanXoaMouseExited
        buttonXacNhanXoa.setBackground(new Color(34, 139, 34));
    }//GEN-LAST:event_buttonXacNhanXoaMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManHinhXacNhanXoaCauHoiIQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManHinhXacNhanXoaCauHoiIQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManHinhXacNhanXoaCauHoiIQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManHinhXacNhanXoaCauHoiIQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManHinhXacNhanXoaCauHoiIQ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonHuyXoa;
    private javax.swing.JButton buttonXacNhanXoa;
    private javax.swing.JLabel labelXacNhanXoa;
    private javax.swing.JPanel panelXacNhanXoaCauHoi;
    // End of variables declaration//GEN-END:variables
}
