/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DTO.QuestionSetDTO;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Random;
import javax.swing.ButtonGroup;

/**
 *
 * @author TUF
 */
public class ManHinhCauHoi extends javax.swing.JFrame {

    public static int dapAn = 0;
    public ButtonGroup group = new ButtonGroup();
    public static DTO.QuestionSetDTO QuestionSet = new QuestionSetDTO();
    public static int i=0;
    public int getRandomNumberUsingNextInt(int min, int max) {
        Random random = new Random();
        return random.nextInt(max - min) + min;
    }
    

    
    public void showQuestionToGUI(int i){
            int j=1;
            QuestionSet = DAO.QuestionSetDAO.getQuestionSet(j);
//            System.out.println(QuestionSet.getQuestionArrayList());
            labelCauHoi.setText(QuestionSet.getQuestionArrayList().get(i).getContent());
            buttonDapAnA.setText(QuestionSet.getQuestionArrayList().get(i).getOption1());
            buttonDapAnB.setText(QuestionSet.getQuestionArrayList().get(i).getOption2());
            buttonDapAnC.setText(QuestionSet.getQuestionArrayList().get(i).getOption3());
            buttonDapAnD.setText(QuestionSet.getQuestionArrayList().get(i).getOption4());
        
    }
    
        public static void wait(int ms)
    {
        try
        {
            Thread.sleep(ms);
        }
        catch(InterruptedException ex)
        {
            Thread.currentThread().interrupt();
        }
    }
    /**
     * Creates new form ManHinhDangNhap
     */

    public ManHinhCauHoi() {
        initComponents();
        showQuestionToGUI(i);
        

//        public void swapArrayCauHoi() {
//        //Hàm này có chức năng tráo đổi thứ tự câu hỏi và thứ tự đáp án
//        for (int i = 0; i < arrcauhoi.size(); i++) {
//            Collections.swap(arrcauhoi, new Random().nextInt(arrcauhoi.size()), new Random().nextInt(arrcauhoi.size()));
//        }
//        for (ModelCauHoi x : arrcauhoi) {//tráo đổi đáp án của từng câu hỏi
//            swapDapAn(x);
//        }
//    }
//
//    public void swapDapAn(ModelCauHoi cauHoi) {
//        //hàm này có chức năng tráo đổi vị trí 4 đáp án
//        ArrayList<String> arr = new ArrayList<>();
//        //thêm 4 câu hỏi vào arr
//        arr.add(cauHoi.getDapan1());
//        arr.add(cauHoi.getDapan2());
//        arr.add(cauHoi.getDapan3());
//        arr.add(cauHoi.getDapan4());
//        Collections.shuffle(arr);//tráo đáp án
//        cauHoi.setDapan1(arr.get(0));
//        cauHoi.setDapan2(arr.get(1));
//        cauHoi.setDapan3(arr.get(2));
//        cauHoi.setDapan4(arr.get(3));
//    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelManHinhChaoMung = new javax.swing.JPanel();
        labelTranhTai = new javax.swing.JLabel();
        labelKienThuc = new javax.swing.JLabel();
        labelButtonKetThuc = new javax.swing.JLabel();
        labelBanQuyenThuocVe = new javax.swing.JLabel();
        labelCauHoi = new javax.swing.JLabel();
        buttonDapAnA = new javax.swing.JButton();
        buttonDapAnB = new javax.swing.JButton();
        buttonDapAnC = new javax.swing.JButton();
        buttonDapAnD = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelManHinhChaoMung.setBackground(new java.awt.Color(255, 255, 255));

        labelTranhTai.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        labelTranhTai.setText("TRANH TÀI");

        labelKienThuc.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelKienThuc.setText("KIẾN THỨC");

        labelButtonKetThuc.setBackground(new java.awt.Color(255, 0, 51));
        labelButtonKetThuc.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelButtonKetThuc.setForeground(new java.awt.Color(255, 255, 255));
        labelButtonKetThuc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelButtonKetThuc.setText("x");
        labelButtonKetThuc.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        labelButtonKetThuc.setOpaque(true);
        labelButtonKetThuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelButtonKetThucMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelButtonKetThucMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelButtonKetThucMouseExited(evt);
            }
        });

        labelBanQuyenThuocVe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelBanQuyenThuocVe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBanQuyenThuocVe.setText("Bản quyền thuộc về Trường Đại học Sài Gòn - 2022");

        labelCauHoi.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelCauHoi.setText("[Vị trí đặt câu hỏi]");

        buttonDapAnA.setBackground(new java.awt.Color(0, 102, 255));
        buttonDapAnA.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        buttonDapAnA.setForeground(new java.awt.Color(255, 255, 255));
        buttonDapAnA.setText("[Đáp án A]");
        buttonDapAnA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonDapAnAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonDapAnAMouseExited(evt);
            }
        });
        buttonDapAnA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDapAnAActionPerformed(evt);
            }
        });

        buttonDapAnB.setBackground(new java.awt.Color(0, 102, 255));
        buttonDapAnB.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        buttonDapAnB.setForeground(new java.awt.Color(255, 255, 255));
        buttonDapAnB.setText("[Đáp án B]");
        buttonDapAnB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonDapAnBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonDapAnBMouseExited(evt);
            }
        });
        buttonDapAnB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDapAnBActionPerformed(evt);
            }
        });

        buttonDapAnC.setBackground(new java.awt.Color(0, 102, 255));
        buttonDapAnC.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        buttonDapAnC.setForeground(new java.awt.Color(255, 255, 255));
        buttonDapAnC.setText("[Đáp án C]");
        buttonDapAnC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonDapAnCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonDapAnCMouseExited(evt);
            }
        });
        buttonDapAnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDapAnCActionPerformed(evt);
            }
        });

        buttonDapAnD.setBackground(new java.awt.Color(0, 102, 255));
        buttonDapAnD.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        buttonDapAnD.setForeground(new java.awt.Color(255, 255, 255));
        buttonDapAnD.setText("[Đáp án D]");
        buttonDapAnD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonDapAnDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonDapAnDMouseExited(evt);
            }
        });
        buttonDapAnD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDapAnDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelManHinhChaoMungLayout = new javax.swing.GroupLayout(panelManHinhChaoMung);
        panelManHinhChaoMung.setLayout(panelManHinhChaoMungLayout);
        panelManHinhChaoMungLayout.setHorizontalGroup(
            panelManHinhChaoMungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelBanQuyenThuocVe, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(panelManHinhChaoMungLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelManHinhChaoMungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCauHoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelManHinhChaoMungLayout.createSequentialGroup()
                        .addComponent(labelTranhTai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelKienThuc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelButtonKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelManHinhChaoMungLayout.createSequentialGroup()
                        .addComponent(buttonDapAnA, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonDapAnB, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelManHinhChaoMungLayout.createSequentialGroup()
                        .addComponent(buttonDapAnC, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonDapAnD, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelManHinhChaoMungLayout.setVerticalGroup(
            panelManHinhChaoMungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelManHinhChaoMungLayout.createSequentialGroup()
                .addGroup(panelManHinhChaoMungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelButtonKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTranhTai)
                    .addComponent(labelKienThuc))
                .addGap(64, 64, 64)
                .addComponent(labelCauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelManHinhChaoMungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDapAnA, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDapAnB, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelManHinhChaoMungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDapAnC, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDapAnD, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addComponent(labelBanQuyenThuocVe)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelManHinhChaoMung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelManHinhChaoMung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void labelButtonKetThucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelButtonKetThucMouseClicked
        System.exit(0);
    }//GEN-LAST:event_labelButtonKetThucMouseClicked

    private void labelButtonKetThucMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelButtonKetThucMouseEntered
        labelButtonKetThuc.setBackground(new Color(204, 0, 51));
    }//GEN-LAST:event_labelButtonKetThucMouseEntered

    private void labelButtonKetThucMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelButtonKetThucMouseExited
        labelButtonKetThuc.setBackground(new Color(255, 0, 51));
    }//GEN-LAST:event_labelButtonKetThucMouseExited

    private void buttonDapAnAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDapAnAMouseEntered
        if (dapAn != 1)
            buttonDapAnA.setBackground(new Color(0, 0, 204));
    }//GEN-LAST:event_buttonDapAnAMouseEntered

    private void buttonDapAnAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDapAnAMouseExited
        if (dapAn != 1)
            buttonDapAnA.setBackground(new Color(0, 102, 255));
    }//GEN-LAST:event_buttonDapAnAMouseExited

    private void buttonDapAnBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDapAnBMouseEntered
        if (dapAn != 2)
            buttonDapAnB.setBackground(new Color(0, 0, 204));
    }//GEN-LAST:event_buttonDapAnBMouseEntered

    private void buttonDapAnBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDapAnBMouseExited
        if (dapAn != 2)
            buttonDapAnB.setBackground(new Color(0, 102, 255));
    }//GEN-LAST:event_buttonDapAnBMouseExited

    private void buttonDapAnCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDapAnCMouseEntered
        if (dapAn != 3)
            buttonDapAnC.setBackground(new Color(0, 0, 204));
    }//GEN-LAST:event_buttonDapAnCMouseEntered

    private void buttonDapAnCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDapAnCMouseExited
        if (dapAn != 3)
            buttonDapAnC.setBackground(new Color(0, 102, 255));
    }//GEN-LAST:event_buttonDapAnCMouseExited

    private void buttonDapAnDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDapAnDMouseEntered
        if (dapAn != 4)
            buttonDapAnD.setBackground(new Color(0, 0, 204));
    }//GEN-LAST:event_buttonDapAnDMouseEntered

    private void buttonDapAnDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDapAnDMouseExited
        if (dapAn != 4)
            buttonDapAnD.setBackground(new Color(0, 102, 255));
    }//GEN-LAST:event_buttonDapAnDMouseExited

    private void buttonDapAnAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDapAnAActionPerformed
        System.out.println(buttonDapAnA.getText());
         if(QuestionSet.getQuestionArrayList().get(i).getOptionTrue().equals(buttonDapAnA.getText()))
            {
                System.out.println("True");               
                buttonDapAnA.setBackground(new Color(255, 255, 0));
                buttonDapAnA.setForeground(new Color(0, 0, 0));
                buttonDapAnB.setEnabled(false);
                buttonDapAnC.setEnabled(false);
                buttonDapAnD.setEnabled(false);
            }
            else
            {
                System.out.println("false");
                showQuestionToGUI(++i);
            }
        buttonDapAnA.setBackground(new Color(0, 0, 204));
        buttonDapAnB.setEnabled(true);
        buttonDapAnA.setEnabled(true);
        buttonDapAnC.setEnabled(true);
        buttonDapAnD.setEnabled(true);
        
        showQuestionToGUI(++i);
    }//GEN-LAST:event_buttonDapAnAActionPerformed

    private void buttonDapAnBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDapAnBActionPerformed
            System.out.println(buttonDapAnB.getText());
         if(QuestionSet.getQuestionArrayList().get(i).getOptionTrue().equals(buttonDapAnB.getText()))
            {
                System.out.println("True"); 
                buttonDapAnB.setBackground(new Color(255, 255, 0));
                buttonDapAnB.setForeground(new Color(0, 0, 0));
                buttonDapAnA.setEnabled(false);
                buttonDapAnC.setEnabled(false);
                buttonDapAnD.setEnabled(false);
            }
            else
            {
                System.out.println("false");
                showQuestionToGUI(++i);
            }
        buttonDapAnB.setBackground(new Color(0, 0, 204));
        buttonDapAnB.setEnabled(true);
        buttonDapAnA.setEnabled(true);
        buttonDapAnC.setEnabled(true);
        buttonDapAnD.setEnabled(true);
        showQuestionToGUI(++i);
    }//GEN-LAST:event_buttonDapAnBActionPerformed

    private void buttonDapAnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDapAnCActionPerformed
        System.out.println(buttonDapAnC.getText());
         if(QuestionSet.getQuestionArrayList().get(i).getOptionTrue().equals(buttonDapAnC.getText()))
            {
                System.out.println("True");
                
                
                buttonDapAnC.setBackground(new Color(255, 255, 0));
                buttonDapAnC.setForeground(new Color(0, 0, 0));
                buttonDapAnA.setEnabled(false);
                buttonDapAnB.setEnabled(false);
                buttonDapAnD.setEnabled(false);
            }
            else
            {
                System.out.println("false");
            }
        buttonDapAnC.setBackground(new Color(0, 0, 204));
        buttonDapAnB.setEnabled(true);
        buttonDapAnA.setEnabled(true);
        buttonDapAnC.setEnabled(true);
        buttonDapAnD.setEnabled(true);
        
        showQuestionToGUI(++i);
    }//GEN-LAST:event_buttonDapAnCActionPerformed

    private void buttonDapAnDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDapAnDActionPerformed
        
         if(QuestionSet.getQuestionArrayList().get(i).getOptionTrue().equals(buttonDapAnD.getText()))
            {
                System.out.println("True");
                buttonDapAnD.setBackground(new Color(255, 255, 0));
                buttonDapAnD.setForeground(new Color(0, 0, 0));
                buttonDapAnA.setEnabled(false);
                buttonDapAnB.setEnabled(false);
                buttonDapAnC.setEnabled(false);
                
            }
            else
            {
                System.out.println("false");
            }
        buttonDapAnD.setBackground(new Color(0, 0, 204));
        buttonDapAnB.setEnabled(true);
        buttonDapAnA.setEnabled(true);
        buttonDapAnC.setEnabled(true);
        buttonDapAnD.setEnabled(true);
        showQuestionToGUI(++i);
    }//GEN-LAST:event_buttonDapAnDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManHinhCauHoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManHinhCauHoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManHinhCauHoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManHinhCauHoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManHinhCauHoi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDapAnA;
    private javax.swing.JButton buttonDapAnB;
    private javax.swing.JButton buttonDapAnC;
    private javax.swing.JButton buttonDapAnD;
    private javax.swing.JLabel labelBanQuyenThuocVe;
    private javax.swing.JLabel labelButtonKetThuc;
    private javax.swing.JLabel labelCauHoi;
    private javax.swing.JLabel labelKienThuc;
    private javax.swing.JLabel labelTranhTai;
    private javax.swing.JPanel panelManHinhChaoMung;
    // End of variables declaration//GEN-END:variables
}
