/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ltm;

import java.awt.Color;
import java.util.*;

/**
 *
 * @author TUF
 */
public class ManHinhChoGhepTran extends javax.swing.JFrame {

    /**
     * Creates new form ManHinhChoGhepTran
     */
    int counter = 60;
    boolean isIt = false;
    
    public ManHinhChoGhepTran() {
        initComponents();
        cacChinhSuaGiaoDienBangCode();
    }
    private void cacChinhSuaGiaoDienBangCode() {
        // Đồng hồ đếm ngược
        Timer timer = new Timer();
        TimerTask task = new TimerTask() {
            public void run() {
                labelDemNguoc.setText(Integer.toString(counter));
                counter = counter - 1;
                if (counter == -1) {
                    timer.cancel();
                } else if (isIt) {
                    timer.cancel();
                    isIt = false;
                }
            }
        };
        timer.scheduleAtFixedRate(task, 1000, 1000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelChoGhepTran = new javax.swing.JPanel();
        labelDangTai = new javax.swing.JLabel();
        buttonHuyCho = new javax.swing.JButton();
        labelDemNguoc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelChoGhepTran.setBackground(new java.awt.Color(255, 255, 255));

        labelDangTai.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelDangTai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDangTai.setText("Đang tìm đối thủ, vui lòng chờ.");

        buttonHuyCho.setBackground(new java.awt.Color(220, 20, 60));
        buttonHuyCho.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonHuyCho.setForeground(new java.awt.Color(255, 255, 255));
        buttonHuyCho.setText("Huỷ chờ");
        buttonHuyCho.setToolTipText("Huỷ chờ");
        buttonHuyCho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonHuyChoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonHuyChoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonHuyChoMouseExited(evt);
            }
        });

        labelDemNguoc.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        labelDemNguoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDemNguoc.setText("60");

        javax.swing.GroupLayout panelChoGhepTranLayout = new javax.swing.GroupLayout(panelChoGhepTran);
        panelChoGhepTran.setLayout(panelChoGhepTranLayout);
        panelChoGhepTranLayout.setHorizontalGroup(
            panelChoGhepTranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChoGhepTranLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(buttonHuyCho, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelChoGhepTranLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelChoGhepTranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDemNguoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelDangTai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelChoGhepTranLayout.setVerticalGroup(
            panelChoGhepTranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChoGhepTranLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(labelDangTai)
                .addGap(18, 18, 18)
                .addComponent(labelDemNguoc, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonHuyCho)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelChoGhepTran, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelChoGhepTran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonHuyChoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHuyChoMouseEntered
        buttonHuyCho.setBackground(new Color(178,34,34));
    }//GEN-LAST:event_buttonHuyChoMouseEntered

    private void buttonHuyChoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHuyChoMouseExited
        buttonHuyCho.setBackground(new Color(220,20,60));
    }//GEN-LAST:event_buttonHuyChoMouseExited

    private void buttonHuyChoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHuyChoMouseClicked
        System.exit(0);
    }//GEN-LAST:event_buttonHuyChoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManHinhChoGhepTran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManHinhChoGhepTran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManHinhChoGhepTran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManHinhChoGhepTran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManHinhChoGhepTran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonHuyCho;
    private javax.swing.JLabel labelDangTai;
    private javax.swing.JLabel labelDemNguoc;
    private javax.swing.JPanel panelChoGhepTran;
    // End of variables declaration//GEN-END:variables
}
