/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.admin;


import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author TUF
 */
public class ManHinhXacNhanThayDoiSoLuongCauHoi extends javax.swing.JFrame {

    /**
     * Creates new form ManHinhChoGhepTran
     */
    public ManHinhXacNhanThayDoiSoLuongCauHoi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelXacNhanThayDoiSoLuongCauHoi = new javax.swing.JPanel();
        labelXacNhanXoa = new javax.swing.JLabel();
        buttonHuyThayDoi = new javax.swing.JButton();
        buttonXacNhanThayDoi = new javax.swing.JButton();
        textFieldSoLuongCauHoiCanThayDoi = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelXacNhanThayDoiSoLuongCauHoi.setBackground(new java.awt.Color(255, 255, 255));

        labelXacNhanXoa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelXacNhanXoa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelXacNhanXoa.setText("Xác nhận thay đổi số lượng câu hỏi");

        buttonHuyThayDoi.setBackground(new java.awt.Color(220, 20, 60));
        buttonHuyThayDoi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonHuyThayDoi.setForeground(new java.awt.Color(255, 255, 255));
        buttonHuyThayDoi.setText("Huỷ");
        buttonHuyThayDoi.setToolTipText("Huỷ");
        buttonHuyThayDoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonHuyThayDoiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonHuyThayDoiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonHuyThayDoiMouseExited(evt);
            }
        });

        buttonXacNhanThayDoi.setBackground(new java.awt.Color(34, 139, 34));
        buttonXacNhanThayDoi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonXacNhanThayDoi.setForeground(new java.awt.Color(255, 255, 255));
        buttonXacNhanThayDoi.setText("Xác nhận");
        buttonXacNhanThayDoi.setToolTipText("Xác nhận");
        buttonXacNhanThayDoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonXacNhanThayDoiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonXacNhanThayDoiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonXacNhanThayDoiMouseExited(evt);
            }
        });

        textFieldSoLuongCauHoiCanThayDoi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textFieldSoLuongCauHoiCanThayDoi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldSoLuongCauHoiCanThayDoi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textFieldSoLuongCauHoiCanThayDoiKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panelXacNhanThayDoiSoLuongCauHoiLayout = new javax.swing.GroupLayout(panelXacNhanThayDoiSoLuongCauHoi);
        panelXacNhanThayDoiSoLuongCauHoi.setLayout(panelXacNhanThayDoiSoLuongCauHoiLayout);
        panelXacNhanThayDoiSoLuongCauHoiLayout.setHorizontalGroup(
            panelXacNhanThayDoiSoLuongCauHoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelXacNhanThayDoiSoLuongCauHoiLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(buttonXacNhanThayDoi, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(buttonHuyThayDoi, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelXacNhanThayDoiSoLuongCauHoiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelXacNhanThayDoiSoLuongCauHoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelXacNhanXoa, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                    .addGroup(panelXacNhanThayDoiSoLuongCauHoiLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(textFieldSoLuongCauHoiCanThayDoi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelXacNhanThayDoiSoLuongCauHoiLayout.setVerticalGroup(
            panelXacNhanThayDoiSoLuongCauHoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelXacNhanThayDoiSoLuongCauHoiLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(labelXacNhanXoa)
                .addGap(18, 18, 18)
                .addComponent(textFieldSoLuongCauHoiCanThayDoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelXacNhanThayDoiSoLuongCauHoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonHuyThayDoi)
                    .addComponent(buttonXacNhanThayDoi))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelXacNhanThayDoiSoLuongCauHoi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelXacNhanThayDoiSoLuongCauHoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonHuyThayDoiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHuyThayDoiMouseEntered
        buttonHuyThayDoi.setBackground(new Color(178, 34, 34));
    }//GEN-LAST:event_buttonHuyThayDoiMouseEntered

    private void buttonHuyThayDoiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHuyThayDoiMouseExited
        buttonHuyThayDoi.setBackground(new Color(220, 20, 60));
    }//GEN-LAST:event_buttonHuyThayDoiMouseExited

    private void buttonHuyThayDoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHuyThayDoiMouseClicked
        System.exit(0);
    }//GEN-LAST:event_buttonHuyThayDoiMouseClicked

    private void buttonXacNhanThayDoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonXacNhanThayDoiMouseClicked
        String noiDungThongBao = "Thay đổi thành công";
        JOptionPane.showMessageDialog(null, noiDungThongBao, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_buttonXacNhanThayDoiMouseClicked

    private void buttonXacNhanThayDoiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonXacNhanThayDoiMouseEntered
        buttonXacNhanThayDoi.setBackground(new Color(0, 128, 0));
    }//GEN-LAST:event_buttonXacNhanThayDoiMouseEntered

    private void buttonXacNhanThayDoiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonXacNhanThayDoiMouseExited
        buttonXacNhanThayDoi.setBackground(new Color(34, 139, 34));
    }//GEN-LAST:event_buttonXacNhanThayDoiMouseExited

    private void textFieldSoLuongCauHoiCanThayDoiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldSoLuongCauHoiCanThayDoiKeyPressed
        String textFromTextField = textFieldSoLuongCauHoiCanThayDoi.getText();
        int length = textFromTextField.length();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            textFieldSoLuongCauHoiCanThayDoi.setEditable(true);
        } else {
            textFieldSoLuongCauHoiCanThayDoi.setEditable(false);
        }
        if (evt.getKeyChar() == 8) { // 8 là mã ASCII của phím BackSpace
            textFieldSoLuongCauHoiCanThayDoi.setText(textFromTextField.substring(0, length - 1));
        }
    }//GEN-LAST:event_textFieldSoLuongCauHoiCanThayDoiKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManHinhXacNhanThayDoiSoLuongCauHoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManHinhXacNhanThayDoiSoLuongCauHoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManHinhXacNhanThayDoiSoLuongCauHoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManHinhXacNhanThayDoiSoLuongCauHoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManHinhXacNhanThayDoiSoLuongCauHoi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonHuyThayDoi;
    private javax.swing.JButton buttonXacNhanThayDoi;
    private javax.swing.JLabel labelXacNhanXoa;
    private javax.swing.JPanel panelXacNhanThayDoiSoLuongCauHoi;
    private javax.swing.JTextField textFieldSoLuongCauHoiCanThayDoi;
    // End of variables declaration//GEN-END:variables
}
