/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.admin;


import java.awt.Color;

/**
 *
 * @author TUF
 */
public class ManHinhChonCheDoQuanLyAdmin extends javax.swing.JFrame {

    /**
     * Creates new form ManHinhDangNhap
     */
    public ManHinhChonCheDoQuanLyAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelManHinhChonCheDoQuanLyAdmin = new javax.swing.JPanel();
        labelTranhTai = new javax.swing.JLabel();
        labelKienThuc = new javax.swing.JLabel();
        labelButtonQuanLyNguoiChoi = new javax.swing.JLabel();
        labelButtonKetThuc = new javax.swing.JLabel();
        labelBanQuyenThuocVe = new javax.swing.JLabel();
        labelButtonQuanLyCauHoi = new javax.swing.JLabel();
        labelChonCheDoQuanLy = new javax.swing.JLabel();
        labelButtonQuanLyCauHoiIQ = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelManHinhChonCheDoQuanLyAdmin.setBackground(new java.awt.Color(255, 255, 255));

        labelTranhTai.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelTranhTai.setText("TRANH TÀI");

        labelKienThuc.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        labelKienThuc.setText("KIẾN THỨC");

        labelButtonQuanLyNguoiChoi.setBackground(new java.awt.Color(0, 102, 255));
        labelButtonQuanLyNguoiChoi.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        labelButtonQuanLyNguoiChoi.setForeground(new java.awt.Color(255, 255, 255));
        labelButtonQuanLyNguoiChoi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelButtonQuanLyNguoiChoi.setText("Quản lý người chơi");
        labelButtonQuanLyNguoiChoi.setToolTipText("Tìm đối thủ Online");
        labelButtonQuanLyNguoiChoi.setOpaque(true);
        labelButtonQuanLyNguoiChoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelButtonQuanLyNguoiChoiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelButtonQuanLyNguoiChoiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelButtonQuanLyNguoiChoiMouseExited(evt);
            }
        });

        labelButtonKetThuc.setBackground(new java.awt.Color(255, 0, 51));
        labelButtonKetThuc.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelButtonKetThuc.setForeground(new java.awt.Color(255, 255, 255));
        labelButtonKetThuc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelButtonKetThuc.setText("x");
        labelButtonKetThuc.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        labelButtonKetThuc.setOpaque(true);
        labelButtonKetThuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelButtonKetThucMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelButtonKetThucMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelButtonKetThucMouseExited(evt);
            }
        });

        labelBanQuyenThuocVe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelBanQuyenThuocVe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBanQuyenThuocVe.setText("Bản quyền thuộc về Trường Đại học Sài Gòn - 2022");

        labelButtonQuanLyCauHoi.setBackground(new java.awt.Color(0, 102, 255));
        labelButtonQuanLyCauHoi.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        labelButtonQuanLyCauHoi.setForeground(new java.awt.Color(255, 255, 255));
        labelButtonQuanLyCauHoi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelButtonQuanLyCauHoi.setText("Quản lý câu hỏi");
        labelButtonQuanLyCauHoi.setToolTipText("Chơi với máy");
        labelButtonQuanLyCauHoi.setOpaque(true);
        labelButtonQuanLyCauHoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelButtonQuanLyCauHoiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelButtonQuanLyCauHoiMouseExited(evt);
            }
        });

        labelChonCheDoQuanLy.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        labelChonCheDoQuanLy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelChonCheDoQuanLy.setText("Vui lòng chọn chế độ cần quản lý");

        labelButtonQuanLyCauHoiIQ.setBackground(new java.awt.Color(0, 102, 255));
        labelButtonQuanLyCauHoiIQ.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        labelButtonQuanLyCauHoiIQ.setForeground(new java.awt.Color(255, 255, 255));
        labelButtonQuanLyCauHoiIQ.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelButtonQuanLyCauHoiIQ.setText("Quản lý câu hỏi IQ");
        labelButtonQuanLyCauHoiIQ.setToolTipText("Chơi với máy");
        labelButtonQuanLyCauHoiIQ.setOpaque(true);
        labelButtonQuanLyCauHoiIQ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelButtonQuanLyCauHoiIQMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelButtonQuanLyCauHoiIQMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelManHinhChonCheDoQuanLyAdminLayout = new javax.swing.GroupLayout(panelManHinhChonCheDoQuanLyAdmin);
        panelManHinhChonCheDoQuanLyAdmin.setLayout(panelManHinhChonCheDoQuanLyAdminLayout);
        panelManHinhChonCheDoQuanLyAdminLayout.setHorizontalGroup(
            panelManHinhChonCheDoQuanLyAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelBanQuyenThuocVe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelManHinhChonCheDoQuanLyAdminLayout.createSequentialGroup()
                .addGroup(panelManHinhChonCheDoQuanLyAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelManHinhChonCheDoQuanLyAdminLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelButtonKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelManHinhChonCheDoQuanLyAdminLayout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addGroup(panelManHinhChonCheDoQuanLyAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelButtonQuanLyCauHoi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelButtonQuanLyNguoiChoi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelKienThuc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelTranhTai)
                            .addComponent(labelButtonQuanLyCauHoiIQ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelManHinhChonCheDoQuanLyAdminLayout.createSequentialGroup()
                .addGap(0, 228, Short.MAX_VALUE)
                .addComponent(labelChonCheDoQuanLy, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(222, 222, 222))
        );
        panelManHinhChonCheDoQuanLyAdminLayout.setVerticalGroup(
            panelManHinhChonCheDoQuanLyAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelManHinhChonCheDoQuanLyAdminLayout.createSequentialGroup()
                .addComponent(labelButtonKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addComponent(labelTranhTai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelKienThuc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(labelChonCheDoQuanLy)
                .addGap(41, 41, 41)
                .addComponent(labelButtonQuanLyNguoiChoi, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelButtonQuanLyCauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelButtonQuanLyCauHoiIQ, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(labelBanQuyenThuocVe)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelManHinhChonCheDoQuanLyAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelManHinhChonCheDoQuanLyAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void labelButtonKetThucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelButtonKetThucMouseClicked
        System.exit(0);
    }//GEN-LAST:event_labelButtonKetThucMouseClicked

    private void labelButtonKetThucMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelButtonKetThucMouseEntered
        labelButtonKetThuc.setBackground(new Color(204, 0, 51));
    }//GEN-LAST:event_labelButtonKetThucMouseEntered

    private void labelButtonKetThucMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelButtonKetThucMouseExited
        labelButtonKetThuc.setBackground(new Color(255, 0, 51));
    }//GEN-LAST:event_labelButtonKetThucMouseExited

    private void labelButtonQuanLyNguoiChoiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelButtonQuanLyNguoiChoiMouseEntered
        labelButtonQuanLyNguoiChoi.setBackground(new Color(0, 0, 204));
    }//GEN-LAST:event_labelButtonQuanLyNguoiChoiMouseEntered

    private void labelButtonQuanLyNguoiChoiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelButtonQuanLyNguoiChoiMouseExited
        labelButtonQuanLyNguoiChoi.setBackground(new Color(0, 102, 255));
    }//GEN-LAST:event_labelButtonQuanLyNguoiChoiMouseExited

    private void labelButtonQuanLyCauHoiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelButtonQuanLyCauHoiMouseEntered
        labelButtonQuanLyCauHoi.setBackground(new Color(0, 0, 204));
    }//GEN-LAST:event_labelButtonQuanLyCauHoiMouseEntered

    private void labelButtonQuanLyCauHoiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelButtonQuanLyCauHoiMouseExited
        labelButtonQuanLyCauHoi.setBackground(new Color(0, 102, 255));
    }//GEN-LAST:event_labelButtonQuanLyCauHoiMouseExited

    private void labelButtonQuanLyCauHoiIQMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelButtonQuanLyCauHoiIQMouseEntered
        labelButtonQuanLyCauHoiIQ.setBackground(new Color(0, 0, 204));
    }//GEN-LAST:event_labelButtonQuanLyCauHoiIQMouseEntered

    private void labelButtonQuanLyCauHoiIQMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelButtonQuanLyCauHoiIQMouseExited
        labelButtonQuanLyCauHoiIQ.setBackground(new Color(0, 102, 255));
    }//GEN-LAST:event_labelButtonQuanLyCauHoiIQMouseExited

    private void labelButtonQuanLyNguoiChoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelButtonQuanLyNguoiChoiMouseClicked
        GUI.admin.ManHinhQuanLyNguoiChoi ManHinhQuanLyNguoiChoi = new ManHinhQuanLyNguoiChoi();
        ManHinhQuanLyNguoiChoi.setVisible(true);
    }//GEN-LAST:event_labelButtonQuanLyNguoiChoiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManHinhChonCheDoQuanLyAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManHinhChonCheDoQuanLyAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManHinhChonCheDoQuanLyAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManHinhChonCheDoQuanLyAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManHinhChonCheDoQuanLyAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelBanQuyenThuocVe;
    private javax.swing.JLabel labelButtonKetThuc;
    private javax.swing.JLabel labelButtonQuanLyCauHoi;
    private javax.swing.JLabel labelButtonQuanLyCauHoiIQ;
    private javax.swing.JLabel labelButtonQuanLyNguoiChoi;
    private javax.swing.JLabel labelChonCheDoQuanLy;
    private javax.swing.JLabel labelKienThuc;
    private javax.swing.JLabel labelTranhTai;
    private javax.swing.JPanel panelManHinhChonCheDoQuanLyAdmin;
    // End of variables declaration//GEN-END:variables
}
